### ISSUE TITLE
[US] Eu, como Professor, quero estar atrelado a disciplina que estou criando

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#100]
### Descrição

Eu, como Professor, quero estar atrelado a disciplina que estou criando, para agilizar o processo de criação.

### Tarefas
- [x] Fixar o professor logado como um dos professores da disciplina;
- [x] Criar um balão informativo no campo preencher professores.

### Tela
![Captura de tela de 2022-07-20 17-32-24](https://user-images.githubusercontent.com/38890440/180076217-6f58195c-0310-45a4-984e-c50795118f5a.png)

### Critérios de Aceitação

- [ ] Professor logado deve sempre estar atrelado a disciplina na qual ele está criando;
- [ ] Professor poder adicionar 1 ou mais professores a sua disciplina.

**Comment by everjunior** [comment]
**Descrição**
- Eu, como Professor, quero estar atrelado a disciplina que estou criando, para **gerenciá-la**.

**Critérios de Aceitação**
- Professor logado deve sempre estar atrelado a disciplina na qual ele está criando;
- Professor poder adicionar 1 ou mais professores **cadastrados na plataforma à** sua disciplina.
