### ISSUE TITLE
[Melhoria] Correções visuais dos campos de seleção em Criar disciplinas

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#101]
### Descrição

O sistema deve notificar visualmente o usuário, usando a cor azul, a ação de selecionar/ remover uma Área ou subárea e/ou Palavras Chaves, passando mouse por cima da mesma.

### Tarefas
- [x] Remover hover vermelho de remover do campo Área ou subárea;
- [x] Remover hover vermelho de remover do campo Palavras Chaves;
- [x] Usar o hover azul tanto para selecionar quanto para remover Área ou subárea;
- [x] Usar o hover azul tanto para selecionar quanto para remover Palavras Chaves.

### Tela 
![Captura de tela de 2022-07-20 17-40-02](https://user-images.githubusercontent.com/38890440/180077471-61ff3d6e-5a0a-4dd6-9842-dc76972901f8.png)
![Captura de tela de 2022-07-20 17-41-07](https://user-images.githubusercontent.com/38890440/180077691-ab12e48e-43a4-47f3-96e8-4b7ac6031f3b.png)
![Captura de tela de 2022-07-20 17-44-04](https://user-images.githubusercontent.com/38890440/180078188-1a7a83d5-7481-4a9c-a656-d01cb55ebabe.png)
![Captura de tela de 2022-07-20 17-43-57](https://user-images.githubusercontent.com/38890440/180078193-d6449e95-7f03-4e94-9a98-408f08c53c21.png)

### Critérios de Aceitação
- [x] A cor azul notificar visualmente a ação de selecionar/ remover uma Área ou subárea;
- [x] A cor azul notificar visualmente a ação de selecionar/ remover uma Palavras Chaves.

**Comment by everjunior** [comment]
**Descrição**
O sistema deve notificar visualmente o usuário, usando a cor azul, a ação de selecionar/ remover uma Área ou subárea e/ou Palavras Chaves, passando mouse por cima da mesma.

**Critérios de Aceitação**
 - A cor azul notificar visualmente a ação de selecionar/ remover uma Área ou subárea;
 - A cor azul notificar visualmente a ação de selecionar/ remover uma **Palavra-chave.**
