### ISSUE TITLE
[Bugfix] Corrigir Mensagem de erro de validação nos campos dos formulários

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#106]
### Descrição
Issue destinada a correção do uso de artigo na frase de mensagem erro em mínimo de caracteres.

## Comportamento Atual
Quando o erro de mínimo de caracteres é captado, mostrasse uma frase alertando o tal erro. Atualmente a frase mostra uma artigo que, dependendo da frase, pode ser o oposto ao substantivo empregado na frase.

## Comportamento Esperado

Usando o artigo certo na frase ou não usando artigo.

## Possível Solução

Retirar o artigo da frase.

## Passos para Reproduzir

1. Fazer login como professor;
2. Tentar criar uma disciplina;
3. Botar menos que o mínimo de caracteres no campo nome e/ou ementa;
4. A mensagem de erro aparecerá com o artigo invertido.

### Tipo de Usuário
Professor

**Comment by giovannabbottino** [comment]
Ao fazer o teste funcional foi possível perceber que há uma mensagem de erro já existente que não condiz. Recomendado investigar e corrigir.
