### ISSUE TITLE
[US] Eu, como professor, gostaria de ver somente informações importantes na listagem de disciplinas, além de uma coluna com os nomes dos professores responsáveis por cada disciplina

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#109]
### Descrição

Eu, como professor, gostaria de ver somente informações importantes na listagem de disciplinas, além de uma coluna com os nomes dos professores responsáveis por cada disciplina, para se ter uma leitura rápida e efetiva das informações importantes das disciplinas.

### Tela:
![Captura de tela de 2022-07-20 17-16-37](https://user-images.githubusercontent.com/38890440/180073640-dee57e8d-5c85-4013-9291-a7c2a278c248.png)

### Tarefas

- [x] Adição da coluna de professores;
- [x] Remover a coluna de ID da tabela de disciplinas;
- [x] Remover botões de Editar e Excluir da coluna de Botões.

### Critérios de Aceitação

- [x] A Lista de Disciplinas ter a coluna "Professores", com a lista dos professores responsáveis por aquela disciplina;
- [x] A coluna ID ser devidamente retirada;
- [x] Os Botões Editar e Excluir serem devidamente retirados;

**Comment by everjunior** [comment]
**Descrição**
Eu, como professor, gostaria de ver somente informações importantes na listagem de disciplinas, além de uma coluna com os nomes dos professores responsáveis por cada disciplina, para se ter uma leitura rápida e efetiva das informações importantes das disciplinas.

**Critérios de Aceitação**
 - A Lista de Disciplinas ter a coluna "Professores", com a lista dos professores responsáveis por aquela disciplina;
- A coluna ID ser devidamente retirada.
- Os Botões serem devidamente retirados; **(Quais botões são esses? Deixar claro!!)**
