### ISSUE TITLE
[US] Eu, como usuário, gostaria de visualizar as principais informações, resumo e objetivos da PUMA

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#114]
### Descrição
Eu, como usuário, gostaria de visualizar as principais informações, resumo e objetivos da PUMA, para saber mais sobre a plataforma.

### Tarefas
 - Criar novo component para a página;
 - Montar o layout;
 - Inserir os textos dispostos no Figma;

Tela 1
![Pagina inicial disciplinas](https://user-images.githubusercontent.com/87672491/186740341-391ef6ae-10bf-4660-899e-049995ce9ef2.png)

### Critérios de Aceitação
 - [x] Ser possível ler Principais Informações da PUMA;
 - [x] Ser possível ler o Resumo da PUMA;
 - [x] Ser possível ler os Principais Objetivos da PUMA;
 - [x] Todo e qualquer usuário conseguir visualizar principais informações, resumo e objetivos da PUMA.

**Comment by everjunior** [comment]
**Descrição**
Eu, como usuário, gostaria de visualizar as principais informações, **apresentação** e objetivos da PUMA, para saber mais sobre a plataforma.

**Critérios de Aceitação**
- Ser possível ler **as principais** Informações da PUMA; **(quais seriam essas informações se não a apresentação e os objetivos?)**
- Ser possível ler **a apresentação** da PUMA; 
- Ser possível ler os Principais Objetivos da PUMA.
- Todo e qualquer usuário conseguir visualizar principais informações, **apresentação** e objetivos da PUMA.
