### ISSUE TITLE
[US] Eu, como usuário, gostaria de visualizar a lista de disciplinas de projetos cadastradas na PUMA

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#115]
### Descrição
Eu, como usuário, gostaria de visualizar a lista de disciplinas de projetos cadastradas na PUMA, para saber mais sobre possíveis conteúdos de projetos a serem trabalhados.

### Critérios de Aceitação
 - [ ] Todas as disciplinas de projetos da PUMA estarem listadas;
 - [ ] Cada disciplina deve ter uma descrição sobre o que ela é, seus objetivos e como ela trabalha os projetos dentro dela;
 - [ ] Cada disciplina deve disponibiliza sua ementa;
 - [ ] Todo e qualquer usuário conseguir visualizar a lista de disciplinas de projetos cadastradas na PUMA.

**Comment by everjunior** [comment]
**Descrição**
Eu, como usuário, gostaria de visualizar a lista de disciplinas de projetos cadastradas na PUMA, para saber mais sobre possíveis conteúdos de projetos a serem trabalhados.

**Critérios de Aceitação**
- Todas as disciplinas de projetos da PUMA estarem listadas;
- Cada disciplina deve ter **sua** descrição, seus objetivos e **quais são os principais temas** dos projetos **desenvolvidos**;
- Cada disciplina deve **disponibilizar** sua ementa;
- Todo e qualquer usuário conseguir visualizar a lista de disciplinas de projetos cadastradas na PUMA.
