### ISSUE TITLE
[US] Eu, como usuário, gostaria de entender e receber orientações sobre o processo de submissão de projetos na PUMA

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#116]
### Descrição

Eu, como usuário, gostaria de entender e receber orientações sobre o processo de submissão de projetos na PUMA, para ter mais conhecimento como posso fazer uma proposta de projeto.

### Tarefas

- [ ] A página mostrar o processo de submissão dos projetos no PUMA

### Critérios de Aceitação

- [ ] Ter um tutorial na home explicando como submeter um projeto
- [ ] O tutorial precisa ser bem claro e ter informações relevantes a respeito da submissão de projetos

**Comment by everjunior** [comment]
**Descrição**

- Eu, como usuário, gostaria de entender e receber orientações sobre o processo de submissão de projetos na PUMA, para ter mais conhecimento **sobre** como posso fazer uma proposta de projeto.

**Critérios de Aceitação**

-  Ter um tutorial na home explicando como submeter um projeto
- O tutorial **precisa** ser bem claro e ter informações relevantes a respeito da submissão de projetos
