### ISSUE TITLE
[US] Eu, como usuário, gostaria de visualizar os Principais Parceiros que já trabalharam com projetos da PUMA

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#117]
### Descrição
Eu, como usuário, gostaria de visualizar os Principais Parceiros que já trabalharam com projetos da PUMA, para visualizar o alcance dos resultados dos projetos.

#### Tela 1
![Captura de tela 2022-08-25 150434](https://user-images.githubusercontent.com/100169943/186738254-5e96e1c2-b66a-4d4b-af9f-1813c19c4926.png)

### Critérios de Aceitação
- [ ] Todos os Principais Parceiros que já trabalharam com projetos da PUMA estarem listados na plataforma;
- [ ] Cada Principal Parceiro ter uma descrição do trabalho dele dentro da PUMA;
- [ ] Cada Principal Parceiro ter os resultados de seus projetos desenvolvidos na PUMA;
- [ ] Todo e qualquer usuário conseguir visualizar os Principais Parceiros que já trabalharam com projetos da PUMA.

**Comment by everjunior** [comment]
**Descrição**
Eu, como usuário, gostaria de visualizar os Principais Parceiros que já trabalharam com projetos da PUMA, para visualizar o alcance dos resultados dos projetos.

**Critérios de Aceitação**
- Todos os Principais Parceiros que já trabalharam com projetos da PUMA estarem listados na plataforma;
- Cada Principal Parceiro **ter um link para o seu site** dentro da PUMA;
- Cada Principal Parceiro ter os resultados de seus projetos desenvolvidos na PUMA; (**Isso aqui não entrará na história sobre os melhores projetos na home? Essa história está faltando ou será validada mais para frente?**)
- Todo e qualquer usuário conseguir visualizar os Principais Parceiros que já trabalharam com projetos da PUMA.

**Comment by giovannabbottino** [comment]
Precisamos do prototipo pronto.

**Comment by bhsouza** [comment]
Devido a não saber como funciona o relatório e como ele se integra ao projeto, a parte de visualizador de pdf não será desenvolvida por fugir do escopo atual.
