### ISSUE TITLE
[US] Eu, como usuário, gostaria de visualizar o Contato dos responsáveis pela PUMA

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#118]
### Descrição
Eu, como usuário, gostaria de visualizar o Contato dos responsáveis pela PUMA, para contactar os responsáveis pela plataforma.
![image](https://user-images.githubusercontent.com/87884030/187317693-c97ab538-c652-4421-8fac-97b45b53b299.png)

### Critérios de Aceitação
- [ ] Todos os Contato dos Responsáveis pela PUMA estarem listados na plataforma;
- [ ] Cada responsável pela PUMA ter seu email institucional informado;
- [ ] Todo e qualquer usuário conseguir ter acesso ao Contato dos responsáveis pelo PUMA.

**Comment by everjunior** [comment]
**Descrição**
Eu, como usuário, gostaria de visualizar o Contato dos responsáveis pela PUMA, para **contactá-los, caso necessário.**

**Critérios de Aceitação**
 Todos os **Contatos** dos Responsáveis pela PUMA estarem listados na plataforma;
 Cada responsável pela PUMA ter seu email institucional informado;
 Todo e qualquer usuário conseguir ter acesso ao Contato dos responsáveis pelo PUMA.
