### ISSUE TITLE
[US] Eu, como usuário, gostaria de ter acesso a página de login enquanto estiver navegando pela Home da PUMA

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#123]
### Descrição
Eu, como usuário, gostaria de ter acesso a página de login enquanto estiver navegando pela Home da PUMA, para ter acesso a plataforma de forma rápida.

### Critérios de Aceitação
- [ ] Ter na home um botão que leva para a página de Login.
- [ ] Esse botão estar localizado em um lugar de fácil visibilidade

**Comment by everjunior** [comment]
**Ok, validada.**
