### ISSUE TITLE
Adicionar resultados dos testes funcionais

### ISSUE THREAD

**Issue by codehg** [fga-eps-mds/2022-1-PUMA-Doc#149]
### Descrição

Os testes funcionais foram realizados pela equipe de PSP5. O relatório deve estar
disponível na wiki do projeto em uma aba chamada Resultado dos Testes

### Tarefas

- [x] Adicionar resultado da R1
- [x] Adicionar o resultado da R2
- [x] Adicionar o resultado da R3
- [x] Configurar aba "Testes no mkdocs"

### Critérios de Aceitação

- Os textos devem estar estruturados de forma legível, respeitando a estrutura do documento recebido.

**Comment by giovannabbottino** [comment]
Tem que verificar se os testes realmente se tratam de releases, @AnHoff consegue fazer isso?
