### ISSUE TITLE
Levantar 3 Riscos do Projeto e como eles o impactam atualmente 

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#153]
### Descrição
Issue destinada ao Levantamento dos 3 Riscos que mais impactam o projeto atualmente. 

### Tarefas
- [x] Atualizar os Riscos;
- [x] Atualizar o EVM;
- [x] Atualizar a Planilha de Custos;
- [x] Levantar Risco 1
- [x] Planejar Modo de Mitigação para o Risco 1;
- [x] Levantar Risco 2
- [x] Planejar Modo de Mitigação para o Risco 2;
- [x] Levantar Risco 3
- [x] Planejar Modo de Mitigação para o Risco 3;

### Critérios de Aceitação
- [x] Levantar Risco 1, 2 e 3;
- [x] Planejar Modo de Mitigação para o Risco 1, 2 e 3;

**Comment by giovannabbottino** [comment]
Atualizei a planilha do EVM: 
https://docs.google.com/spreadsheets/d/1IhuQZnWB7x9qGNZbvIPSti8ktab9B11mJ15ur2vMqI4/edit?usp=sharing
O plano de custos https://docs.google.com/spreadsheets/d/1oA_S1x2kdo0qmJlyT4jMZZx1hzPHDg9pbpKejKWj4Ms/edit?usp=sharing 
E o gerenciamento de riscos: https://docs.google.com/spreadsheets/d/1uEExKMukGKtuFZKjP3avVxyMZfte7idBnHzgJpcurHU/edit?usp=sharing

**Comment by giovannabbottino** [comment]
Riscos gerei os gráficos

![image](https://user-images.githubusercontent.com/31159235/189449037-acae2a51-ec95-4e11-92a3-cbb1ad882348.png)

![image](https://user-images.githubusercontent.com/31159235/189449075-7bb4ad6d-85a7-40c8-be72-8a9e479bbe22.png)

**Comment by giovannabbottino** [comment]
Gerei um gráfico: Valor Planejado por Release e Valor Agregado por release  por release 

![image](https://user-images.githubusercontent.com/31159235/189449156-b3a96814-0b3a-4dc6-8f88-ca8c68a50d97.png)

**Comment by giovannabbottino** [comment]
Gerei um velocity
![image](https://user-images.githubusercontent.com/31159235/189449255-1801a5e5-f076-44b1-bd90-75b98fb11c1c.png)

**Comment by giovannabbottino** [comment]
Apresentação: https://www.canva.com/design/DAFFB1JZMM4/jLvW0b9tt6r-QdAIjDZRSw/edit?utm_content=DAFFB1JZMM4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by giovannabbottino** [comment]
Após a apresentação foi levantado que devemos refazer o grafico de EVM
