### ISSUE TITLE
Compreender Arquitetura

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#18]
### Descrição
Compreender a arquitetura utilizada por projetos passados para incrementar com novas features.

### Tarefa
- [x] Revisar Arquitetura
- [x] Definir novas features pelo Lein Inception
- [x] Adaptar arquitetura para as novas features

**Comment by giovannabbottino** [comment]
É preciso fazer o novo documento de arquitetura, issue urgente para a próxima semana
