### ISSUE TITLE
Discussão de Funcionalidades já entregues e Melhorias

### ISSUE THREAD

**Issue by codehg** [fga-eps-mds/2022-1-PUMA-Doc#22]
### Descrição

Issue destinada a avaliação inicial do estado atual do produto e lavantamento de questões e possíveis melhorias por parte do time do Gama.

Debater com o time Darcy o escopo detalhado de melhorias necessárias no produto. 
**Data da Reunião com os clientes**: 06/07

### Tarefas
- [x] Discutir na reunião semanal o escopo detalhado de melhorias necessárias no produto;
- [ ] Definir um planejamento para levantamento e validação do Product Backlog.

### Critério de Aceitação
- [ ] Grupo ter debatido e levantado o escopo detalhado de melhorias necessárias no produto;

**Comment by Bruno-Felix** [comment]
Eu, @Bruno-Felix  fiz uma análise superficial e simples do produto em seu estado atual. Somente navegando pela aplicação testando as funcionalidades já desenvolvidas.

Tive os seguintes questionamento:

# Bugs

### Bugs reportados no Repositório do Semestre Anterior

- **[BUG] Cadastro de novo usuário!**
    - [https://github.com/fga-eps-mds/2021-2-PUMA-Doc/issues/102](https://github.com/fga-eps-mds/2021-2-PUMA-Doc/issues/102)

---
## Páginas/ Perfil

### Agente Externo

- Quem sou eu?, Seria interessante a visualização do nome de quem está logado na aplicação.

### Palavras Chave

- Palavras Chave X Áreas e Subáreas X Palavras Chave Principal

### Cadastrar Disciplina

- Toda Disciplina tenho que criar uma palavra-chave nova?
- Para o que serve "Áreas e Subáreas do conhecimento" atualmente?

### Excluir Disciplina

- Excluir uma disciplina que tem projetos propostos não deveria realocar a disciplina?

### Projetos da Disciplina

- Precisa de paginação?

# Quais Melhorias a mais devem ser feitas?

**Comment by Bruno-Felix** [comment]
Na Reunião Semanal realizada dia 06/07, foi constatado inúmeras falhas entre ambos os times, Darcy e Gama.

### Gama:
- Pouca Organização e Planejamento;
- Necessidade de definir, previamente, uma pauta de projeto.
