### ISSUE TITLE
Desenvolver Documento de Arquitetura

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#32]
### Descrição

Desenvolver e adicionar ao github pages o documento de arquitetura

### Tarefas

- [x] Adicionar ao mkdocs
- [x] Desenvolver e documentar a arquitetura

### Critérios de Aceitação

- [x] Documento de arquitetura no github pages

**Comment by giovannabbottino** [comment]
Esse doc tem que ter: 

- [ ] Tabela de versão
- [ ] Introdução
- [ ] Diagrama de relações
- [ ] Representação dos Serviços
- [ ] Tecnologias 
- [ ] Diagrama Entidade-Relacionamento
- [ ] Diagrama Lógico de Dados
- [ ] Dicionario de Dados
- [ ] Referencia

Podem dar uma olhada nos ultimos semestres : https://fga-eps-mds.github.io/2021-2-PUMA-Doc/produto/arquitetura/
https://fga-eps-mds.github.io/2021-1-PUMA/#/bancodedados/bancos-de-dados
https://fga-eps-mds.github.io/2021-1-PUMA/#/planejamento/doc-de-arquitetura
