### ISSUE TITLE
Desenvolver Plano de Comunicação

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#39]
### Descrição

Desenvolver plano de comunicação, ferramentas, horários e reuniões fixas. 

### Tarefas

- [x] Desenvolver plano 
- [x]  Atualizar quadro de disponibilidade 

### Critérios de Aceitação

- [x] Plano de comunicação no mkdocs

**Comment by giovannabbottino** [comment]
O MDS Eduardo deveria ter participado, mas não respondeu minhas mensagens
