### ISSUE TITLE
Documentar Quadro de Conhecimento

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#40]
### Descrição
 Documentar e adicionar ao github pages o quadro de conhecimento. Vinculada a issue #9  

### Tarefas

- [x] Adicionar ao mkdocs
- [x] Documentar o quadro de conhecimento

### Critérios de Aceitação

- [x] Quadro de conhecimento no github pages

**Comment by giovannabbottino** [comment]
Issue feita com o MDS @GabriellCabrall 
Foi necessário realizar um novo arquivo de quadro de conhecimento
