### ISSUE TITLE
Desenvolver Plano de Custos

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#41]
### Descrição

Desenvolver e adicionar ao github pages o plano de custos.

### Tarefas

- [x] Adicionar ao mkdocs
- [x] Desenvolver e documentar Plano de custos

### Critérios de Aceitação

- [x] Plano de custos no github pages

**Comment by santosm46** [comment]
Issue feita com a MDS [Ana Hoffmann](https://github.com/AnHoff)
