### ISSUE TITLE
Importar repositórios

### ISSUE THREAD

**Issue by codehg** [fga-eps-mds/2022-1-PUMA-Doc#45]
### Descrição

Os repositórios devem conter a rastreabilidade do desenvolvimento dos semestres anteriores. Para isso, os repositórios devem ser recriados com o método "import".

### Tarefas

- [x] Recriar os repositórios de código

### Critérios de Aceitação

- Todos os repositórios criados com o padrão de nomeação 2022-1-PUMA
- Commits anteriores devem ser preservados

**Comment by giovannabbottino** [comment]
:heavy_check_mark:
