### ISSUE TITLE
Desenvolver Documento de Metodologia

### ISSUE THREAD

**Issue by santosm46** [fga-eps-mds/2022-1-PUMA-Doc#60]
### Descrição

Issue destinada ao desenvolvimento do Documento sobre as metodologias utilizadas no planejamento e desenvolvimento do projeto PUMA.

### Tarefas

- [ ] tarefa 1
- [ ] tarefa 2

### Critérios de Aceitação

- criterio de aceitacao 1

**Comment by giovannabbottino** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PUMA-20221-62be2198257e9300192df019/issues/fga-eps-mds/2022-1-PUMA-Doc/60?planning-poker) with ZenHub @santosm46
