### ISSUE TITLE
Revisar Documentação

### ISSUE THREAD

**Issue by codehg** [fga-eps-mds/2022-1-PUMA-Doc#61]
### Descrição

Revisar a documentação para que as informações estejam atualizadas conforme
o desenvolvimento das últimas semanas.

### Tarefas
- [x] Verificar ortografia
- [x] Validar desenvolvimento
- [x] Adicionar alterações 

### Critérios de Aceitação
* Documentos estarem bem escritos e atenderem a proposta.

**Comment by Bruno-Felix** [comment]
Link da GitHub page está no campo "About" na home do repositório do projeto.

**Comment by Bruno-Felix** [comment]
Seria interessante:
### MenuBar:
- Todos os Nomes serem padronizados com a letra inicial Maiúscula;
- Retirar o "sprint x" tanto das plannings tanto das reviews. Não faz sentido ser "Planning Sprint 3" sendo que já está dentro do tópico "Sprint 3".

### Documentos:
- Seguir a estrutura:
   - Introdução;
   - Metodologia(caso necessário)
   - _Desenvolvimento do Documento Normal_
   - Referencia
   - Versionamento*.
- Todas as imagens dos documentos terem legenda que são links. Ao clicar abre a imagem em outra aba, maior.(Nos docs da review tem o exemplo no burndown e velocity, basta copiar)

* Versionamento q não é legal estar no inicio do documento, mas sim no final.

**Comment by Bruno-Felix** [comment]
Necessidade ser Desenvolvido @codehg:

### Documento de Visão:
- Atualizar Funcionalidades;
- Atualizar Sequenciador;
- Atualizar Canvas.

**Comment by Bruno-Felix** [comment]
Essa issue também será usada para Correções Macros de Repositório para a Release 1
