### ISSUE TITLE
Documentar Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by AnHoff** [fga-eps-mds/2022-1-PUMA-Doc#65]
### Descrição
Desenvolver e adicionar ao repositório a documentação do protótipo de alta fidelidade do projeto.

### Tarefas
- [x] Reunir imagens gerais do protótipo
- [x] Criar documento com breve explicação do protótipo existente

### Critérios de Aceitação
- Documento ilustrativo e descritivo sobre o protótipo.

**Comment by giovannabbottino** [comment]
Fiquem de olho em seguir o padrão dos commits
