### ISSUE TITLE
[Bugfix] Validar campos obrigatórios no cadastro

### ISSUE THREAD

**Issue by giovannabbottino** [fga-eps-mds/2022-1-PUMA-Doc#67]
### Descrição

Não há validação ao usuário sobre dados obrigatórios não inseridos na primeira verificação.

## Comportamento Atual

Sistema permite seguir o cadastro, mesmo sem ter informado dados obrigatórios. Só faz a validação quando estou na segunda tela 2, que ele não permite finalizar o cadastro.

### Tela 1
![image](https://user-images.githubusercontent.com/31159235/179416631-1f87360b-d490-42fd-a5be-02a9c9fe8db4.png)

### Tela 2
![image](https://user-images.githubusercontent.com/31159235/179416649-8c561b3f-047f-46e5-98ba-aa18d0e6412d.png)

### Tela 3
![image](https://user-images.githubusercontent.com/31159235/179417036-6d7a467d-7716-44ae-9d51-8d56f9d0f0cf.png)

## Comportamento Esperado

O sistema deveria verificar os dados obrigatórios na tela 1, antes de avançar para a tela 2.

## Passos para Reproduzir

1. Vá para Cadastro de usuário
2. Não preencha informações necessárias
3. Avance para a próxima tela
4. Tente cadastras o usuário

### Browser
Google Chrome

### Tipo de Usuário
Qualquer tipo de usuário tentando cadastrar.

**Comment by AnHoff** [comment]
Optamos por fazer uma validação de preenchimento, de modo que, ao clicar na setinha para avançar à próxima página enquanto algum campo esteja preenchido incorretamente, o usuário verá uma mensagem exigindo que os dados sejam preenchidos corretamente e será impedido de avançar para a próxima página.
Ainda precisamos melhorar como está sendo feita a verificação dos dados inseridos.


![PUMA-cadastro-validar](https://user-images.githubusercontent.com/87672491/181565340-497af3aa-b55b-4562-841a-ebfb25668cb1.png)
