### ISSUE TITLE
[Bugfix] Validar telefone de usuário no cadastro

### ISSUE THREAD

**Issue by giovannabbottino** [fga-eps-mds/2022-1-PUMA-Doc#68]
### Descrição

Não há validação ao cadastrar um usuário com telefone invalido. 

## Comportamento Atual

O sistema permite que o usuário cadastre um telefone inválido.
### Tela 1
![image](https://user-images.githubusercontent.com/31159235/179417764-fa2040eb-fedf-4367-8ee9-8c7e53eb0256.png)

## Comportamento Esperado

O sistema validar o telefone

## Possível Solução

Se voce digitar os parenteses
```^\\([0-9]{2}\\)((3[0-9]{3}-[0-9]{4})|(9[0-9]{3}-[0-9]{5}))$```
 
Se voce só digitar numeros
```^\\([0-9]{2}\\)((3[0-9]{7})|(9[0-9]{8}))$```

## Passos para Reproduzir

1. Ao cadastrar um novo usuário
2. Preencher com telefone invalido
3. Siga para cadastrar o usuário

### Browser
Google Chrome
### Tipo de Usuário
Qualquer usuário ao tentar cadastrar.

**Comment by codehg** [comment]
Talvez seja necessário alterar a validação dessa regex no componente que valida as máscaras

https://github.com/fga-eps-mds/2022-1-PUMA-Frontend/blob/dev/puma/src/utils/validators-puma.js
