### ISSUE TITLE
[Bugfix] Validação nome de Disciplina em Criar Disciplina

### ISSUE THREAD

**Issue by giovannabbottino** [fga-eps-mds/2022-1-PUMA-Doc#70]
### Descrição

O sistema não verifica a quantidade de caracteres do nome de uma disciplina. 

## Comportamento Atual

O sistema permite cadastrar disciplina somente de uma letra. 

### Tela 1
![image](https://user-images.githubusercontent.com/31159235/179418855-c46eb3d1-df72-4e14-b32b-859626974327.png)

## Comportamento Esperado

O sistema deve exigir no mínimo 10 caracteres. 

## Possível Solução

Utilizando Vee-Validate

## Passos para Reproduzir

1. Faça login como professor
2. Comece a cadastrar uma disciplina
3. Escreva um nome de menos de 10 caracteres
4. Cadastre a disciplina

### Browser
Google Chrome
### Tipo de Usuário
Professor

**Comment by enzoggqs** [comment]
Verdade, verifiquei isto também no teste aqui!!

**Comment by Bruno-Felix** [comment]
O Bugfix foi implementado e aprovado com sucesso pelo Cliente.

Porém se apontou uma outra melhoria nos caracteres do campo de Criar Disciplinas que será implementada futuramente.
