### ISSUE TITLE
[US] Eu, como usuário, desejo visualizar o nome do perfil logado

### ISSUE THREAD

**Issue by giovannabbottino** [fga-eps-mds/2022-1-PUMA-Doc#78]
### Descrição

Eu, como usuário, gostaria de visualizar o perfil do usuário logado, para que tenha o controle do tipo do perfil e que perfil é esse que estou realizando minhas atividades.

### Tarefas

- [ ] Adicionar o nome do usuário ao canto superior direito;
- [ ] Adicionar o tipo de perfil do usuário.

#### Tela 1
![Captura de tela 2022-08-22 190319](https://user-images.githubusercontent.com/100169943/186026744-8e6bd178-33f6-426b-a17f-6b2941d87089.png)

### Critérios de Aceitação

- [ ] Ser possível visualizar o tipo do perfil do usuário logado;
- [ ] Ser possível visualizar nome do usuário logado.

**Comment by everjunior** [comment]
**Descrição**
Eu, como usuário, gostaria de visualizar o perfil do usuário logado, para que tenha o controle do tipo do perfil e que perfil é esse que estou realizando minhas atividades.

Critérios de Aceitação
 - Ser possível visualizar o tipo do perfil do usuário logado;
 - Ser possível visualizar nome do usuário logado.
 
 **Ok!!**

**Comment by FelipeDireito** [comment]
Já temos o protótipo do Antônio e estamos trabalhando na resolução.
