### ISSUE TITLE
Ajustar Home/ README

### ISSUE THREAD

**Issue by bhsouza** [fga-eps-mds/2022-1-PUMA-Doc#79]
### Descrição
Issue destinada a documentação da Home 

### Tarefas
- [ ]  Documento Home/ README
 
### Critérios de Aceitação
- [ ]   Documento completo;
- [ ]   Documento sem erros ortográficos.

**Comment by Bruno-Felix** [comment]
Sugestão de [README](https://github.com/fga-eps-mds/2020.1-VC_Usuario) para talvez inspirar.

**Comment by Bruno-Felix** [comment]
Repositório focado em [READMES](https://github.com/matiassingers/awesome-readme)
