### ISSUE TITLE
[Melhoria] Notificar pesquisa com resultados não encontrados

### ISSUE THREAD

**Issue by giovannabbottino** [fga-eps-mds/2022-1-PUMA-Doc#80]
### Descrição

O Sistema deve notificar o usuário caso a pesquisa não tenha nenhum resultado.

#### Tela 1
![image](https://user-images.githubusercontent.com/31159235/179421168-ca6c7bfe-2e2f-4abb-b655-2c6473c091ce.png)

### Tarefas

- [x] Quando resultado da pesquisa for zero, deve ser apresentado uma mensagem `Resultado não encontrado para a pesquisa realizada`

### Critérios de Aceitação

- [x] Seja possível visualizar a mensagem `Resultado não encontrado para a pesquisa realizada` quando não houver projetos

**Comment by everjunior** [comment]
[Melhoria] Notificar pesquisa **de projetos** com resultados não encontrados #80

**Descrição**

- O Sistema deve notificar o usuário caso a pesquisa **de projetos** não tenha nenhum resultado **encontrado**.

**Critérios de Aceitação**

- Seja possível visualizar a mensagem Resultado não encontrado para a pesquisa realizada quando não houver projetos
