### ISSUE TITLE
[Melhoria] Alterar ordem dos Campos em Criar Projeto

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#81]
### Descrição

A ordem dos campos em Criar Projeto deve ser:
- Título
- Problema
- Resultado Desejado

### Tarefas
- [x] Confirmar a ordem exata com os donos do produto;
- [x] Fazer a alteração das ordens dos campos.

### Critérios de Aceitação

- [ ] A nova ordem está devidamente estabelecida.

**Comment by everjunior** [comment]
**Ok, validada.**
