### ISSUE TITLE
[Bugfix] Corrigir estilo cabeçalho da tabela listagem projetos

### ISSUE THREAD

**Issue by giovannabbottino** [fga-eps-mds/2022-1-PUMA-Doc#82]
### Descrição

O cabeçalho da tabela de projetos das disciplinas está com um layout ruim.

### Tela 1
![image](https://user-images.githubusercontent.com/31159235/179421607-f5077753-45de-457e-815e-9cb02eaea922.png)

## Comportamento Esperado

O cabeçalho da tabela deve estar alinhado

## Possível Solução

Diminuir fonte de cabeçalho de projeto.

## Passos para Reproduzir

1. Faça login como professor
2. Acesse projetos das disciplinas
3. Visualize a tabela

### Browser
Google Chrome 

### Tipo de Usuário
Professor

**Comment by edudsan** [comment]
Durante o Desenvolvimento foi constatado uma certa dificuldade para ajustar o layout dos cabeçalhos. A proposta escolhida foi o que em acordo consideramos o mínimo aceitável.
Sugestão futura: Refatorar a implementação das tabelas.
