### ISSUE TITLE
[Melhoria] Eu, como usuário, gostaria de voltar para a página anterior

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#83]
### Descrição
Eu, como usuário, gostaria de ter um botão para retornar para a tela anterior de onde vim, tendo assim uma melhor navegabilidade dentro do projeto.

### Tela Exemplo
![image](https://user-images.githubusercontent.com/87884030/185478763-0a733c63-ab65-4052-bee6-2d15d7477414.png)

### Tarefas
- [x] Mapear todas as telas/ ações de que se originam de uma tela anterior;
- [x] Criar um component para redirecionamento a tela anterior.

### Critérios de Aceitação

- [ ] Usuário conseguir voltar a tela originária da ação atual, para todas as páginas que necessitam disso.
- [ ] O botão possuir um efeito de hover. Ao passar o cursor em cima, apresentar uma interação conforme a prototipação.

**Comment by YuriBre** [comment]
Recebemos o protótipo feito pelo Antônio e iremos trabalhar nesta issue com base nele.

**Comment by YuriBre** [comment]
Criamos um componente ReturnButton e o chamamos nas devidos locais.

O resultado em uma das telas que necessitavam do botão:
![photo1661178087 (1)](https://user-images.githubusercontent.com/87884030/186008901-7b0542af-127e-49d9-9cd2-e8a909db874b.jpeg)
