### ISSUE TITLE
[Bugfix] Validar campos em Análise da Proposta

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#86]
## Descrição

Os campos em Análise da Proposta estão sem validação de mínimo de caracteres.

## Comportamento Atual
Os campos não tem mínimo de caracteres para preenchimento.

## Tela 1
![image](https://user-images.githubusercontent.com/38890440/179422138-89156524-aea1-488f-ba02-5c09221dd04d.png)

## Comportamento Esperado
Os campos devem ter o mínimo de 10 caracteres.

## Possível Solução

Usar o vee-validate para ditar o mínimo dos caracteres.

## Passos para Reproduzir

1. Faça login como professor;
2. Entre em um projeto proposto;
3. Clique em avaliar projeto.

### Browser
Google Chrome

### Tipo de Usuário
Professor

**Comment by codehg** [comment]
Corrigir descrição da Issue @Bruno-Felix

**Comment by Bruno-Felix** [comment]
> Corrigir descrição da Issue @Bruno-Felix

Voce também pode fazer isso, @codehg
