### ISSUE TITLE
Melhorar Documento Plano de Custos

### ISSUE THREAD

**Issue by AnHoff** [fga-eps-mds/2022-1-PUMA-Doc#93]
### Descrição
Faltam descrições abrangentes sobre o plano de custos já existente.

### Tarefas

- [x] Criar novos tópicos;
- [x] Produzir parágrafos analisando a tabela disponibilizada.

### Critérios de Aceitação

- As melhorias tornam o documento mais detalhado e de fácil entendimento.

**Comment by AnHoff** [comment]
**Opcional:** disponibilizar a tabela existente em um iframe (nesse caso, como uma planilha excel).

**Comment by santosm46** [comment]
Basear no plano de custos de Cartografia social: https://fga-eps-mds.github.io/2021-2-Cartografia-social-Doc/custos/
