### ISSUE TITLE
[US] Eu, como professor, gostaria de ver as minhas disciplinas em destaque

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#98]
### Descrição

Eu, como professor, gostaria de ver minhas disciplinas em destaque, para que tenha uma rápida leitura e entendimento da lista de disciplinas.

### Tela:
![Captura de tela de 2022-07-20 17-16-37](https://user-images.githubusercontent.com/38890440/180073640-dee57e8d-5c85-4013-9291-a7c2a278c248.png)

### Tarefas
- [x] Separação das disciplinas do professor logado das demais disciplinas de outros professores;

### Critérios de Aceitação
- [x] As disciplinas do professor estarem devidamente destacadas das outras disciplinas.

**Comment by AnHoff** [comment]
A dificuldade em finalizar a issue se deve a 2 motivos:

1. A tabela é apenas uma listagem em JavaScript, fato que complica edições visuais;
2. Há certa dificuldade em entender o código relacionado ao cadastro de disciplinas, além de possuir partes incompletas no back-end. Acessar os dados dos professores responsáveis pelas disciplinas não é tão fácil quanto parece.

Melhor caminho a seguir: refazer a página com uma tabela bem feita que possibilite tanto a edição quanto a manutenção no futuro.

**Comment by Bruno-Felix** [comment]
Sugestão de Implementação: 
Cria um novo endpoint para listagem das disciplinas:
{
  disciplinas_do_professor: [object, object]
  demais_disciplinas: [object, object]
}

Esse endpoint poderá receber o id do professor como parâmetro.

Caso o professor tenha disciplinas, disciplinas_do_professor será não nula.
Caso o professor não tenha disciplinas,  disciplinas_do_professor será nula.

**Comment by AnHoff** [comment]
Após @Bruno-Felix conseguir refatorar a tabela, foi possível terminarmos a issue. Segue print da nova tela: 
![image](https://user-images.githubusercontent.com/87672491/185815838-f9fc199f-9700-481a-887e-41d4cb88da47.png)

**Comment by giovannabbottino** [comment]
Ao fazer o teste de funcionalidade o tester achou um comportamento não esperado ao criar uma disciplina.
