### ISSUE TITLE
[Melhoria] Alterar Composição do Formulário de Criar Disciplina

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#99]
### Descrição

Eu, como sistema, gostaria que a tela de Criar Disciplina tivesse uma estrutura mais objetiva e informativa, para auxiliar o professor na criação da disciplina.

### Tarefas
- [x] Trocar de lugar os campos Áreas... Com Palavras Chaves
- [ ] Adição de um balão informativo sobre as palavras chaves;
- [x] Alterar style dos botões de ação.

### Telas
![Captura de tela de 2022-07-20 17-27-20](https://user-images.githubusercontent.com/38890440/180075394-08606cf7-694c-43e3-9d07-ae978ae1e69c.png)
![Captura de tela de 2022-07-20 17-27-08](https://user-images.githubusercontent.com/38890440/180075398-2e61580c-5e4d-4c76-9171-7dc0ed578ee9.png)

### Critérios de Aceitação
- [x] Os campos estarem na devida ordem;
- [ ] O balão informativo do campo palavra chaves mostrar devidamente a informação do que é o campo.

**Comment by AnHoff** [comment]
Recursos adicionados. Porém ainda são necessários ajustes no pop-up.

![image](https://user-images.githubusercontent.com/87672491/190931431-63e09c25-11af-4823-abd7-977a9409394b.png)
